<?php

namespace ContainerZeCxUVt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C67z0NEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.c67z0NE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.c67z0NE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cache' => ['privates', 'cache.app.taggable', 'getCache_App_TaggableService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'team' => ['privates', '.errored..service_locator.c67z0NE.App\\Entity\\Team', NULL, 'Cannot autowire service ".service_locator.c67z0NE": it references class "App\\Entity\\Team" but no such service exists.'],
        ], [
            'cache' => '?',
            'entityManager' => '?',
            'team' => 'App\\Entity\\Team',
        ]);
    }
}
