<?php

namespace ContainerZeCxUVt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FtuIPCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FtuI_pC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FtuI_pC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\PictureController::createPicture' => ['privates', '.service_locator.4I3nfxi', 'get_ServiceLocator_4I3nfxiService', true],
            'App\\Controller\\PictureController::getPicture' => ['privates', '.service_locator.kLAOo3x', 'get_ServiceLocator_KLAOo3xService', true],
            'App\\Controller\\PictureController::softDeletePicture' => ['privates', '.service_locator.3jTAzhM', 'get_ServiceLocator_3jTAzhMService', true],
            'App\\Controller\\RecontreController::getOneRencontre' => ['privates', '.service_locator.8ON5BGE', 'get_ServiceLocator_8ON5BGEService', true],
            'App\\Controller\\RecontreController::getOneTeamRatio' => ['privates', '.service_locator.VbWGi9S', 'get_ServiceLocator_VbWGi9SService', true],
            'App\\Controller\\RecontreController::getRencontreByTeam' => ['privates', '.service_locator.92Obg1q', 'get_ServiceLocator_92Obg1qService', true],
            'App\\Controller\\RecontreController::getRencontres' => ['privates', '.service_locator.VbWGi9S', 'get_ServiceLocator_VbWGi9SService', true],
            'App\\Controller\\TeamController::createTeam' => ['privates', '.service_locator.jnDt8vv', 'get_ServiceLocator_JnDt8vvService', true],
            'App\\Controller\\TeamController::deleteTeam' => ['privates', '.service_locator.c67z0NE', 'get_ServiceLocator_C67z0NEService', true],
            'App\\Controller\\TeamController::getOneTeam' => ['privates', '.service_locator.ONyAqF7', 'get_ServiceLocator_ONyAqF7Service', true],
            'App\\Controller\\TeamController::getTeams' => ['privates', '.service_locator.ONyAqF7', 'get_ServiceLocator_ONyAqF7Service', true],
            'App\\Controller\\TeamController::softDeleteOneTeam' => ['privates', '.service_locator.FuGjA.8', 'get_ServiceLocator_FuGjA_8Service', true],
            'App\\Controller\\TeamController::updateTeam' => ['privates', '.service_locator.Ay17CqL', 'get_ServiceLocator_Ay17CqLService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\PictureController:createPicture' => ['privates', '.service_locator.4I3nfxi', 'get_ServiceLocator_4I3nfxiService', true],
            'App\\Controller\\PictureController:getPicture' => ['privates', '.service_locator.kLAOo3x', 'get_ServiceLocator_KLAOo3xService', true],
            'App\\Controller\\PictureController:softDeletePicture' => ['privates', '.service_locator.3jTAzhM', 'get_ServiceLocator_3jTAzhMService', true],
            'App\\Controller\\RecontreController:getOneRencontre' => ['privates', '.service_locator.8ON5BGE', 'get_ServiceLocator_8ON5BGEService', true],
            'App\\Controller\\RecontreController:getOneTeamRatio' => ['privates', '.service_locator.VbWGi9S', 'get_ServiceLocator_VbWGi9SService', true],
            'App\\Controller\\RecontreController:getRencontreByTeam' => ['privates', '.service_locator.92Obg1q', 'get_ServiceLocator_92Obg1qService', true],
            'App\\Controller\\RecontreController:getRencontres' => ['privates', '.service_locator.VbWGi9S', 'get_ServiceLocator_VbWGi9SService', true],
            'App\\Controller\\TeamController:createTeam' => ['privates', '.service_locator.jnDt8vv', 'get_ServiceLocator_JnDt8vvService', true],
            'App\\Controller\\TeamController:deleteTeam' => ['privates', '.service_locator.c67z0NE', 'get_ServiceLocator_C67z0NEService', true],
            'App\\Controller\\TeamController:getOneTeam' => ['privates', '.service_locator.ONyAqF7', 'get_ServiceLocator_ONyAqF7Service', true],
            'App\\Controller\\TeamController:getTeams' => ['privates', '.service_locator.ONyAqF7', 'get_ServiceLocator_ONyAqF7Service', true],
            'App\\Controller\\TeamController:softDeleteOneTeam' => ['privates', '.service_locator.FuGjA.8', 'get_ServiceLocator_FuGjA_8Service', true],
            'App\\Controller\\TeamController:updateTeam' => ['privates', '.service_locator.Ay17CqL', 'get_ServiceLocator_Ay17CqLService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\PictureController::createPicture' => '?',
            'App\\Controller\\PictureController::getPicture' => '?',
            'App\\Controller\\PictureController::softDeletePicture' => '?',
            'App\\Controller\\RecontreController::getOneRencontre' => '?',
            'App\\Controller\\RecontreController::getOneTeamRatio' => '?',
            'App\\Controller\\RecontreController::getRencontreByTeam' => '?',
            'App\\Controller\\RecontreController::getRencontres' => '?',
            'App\\Controller\\TeamController::createTeam' => '?',
            'App\\Controller\\TeamController::deleteTeam' => '?',
            'App\\Controller\\TeamController::getOneTeam' => '?',
            'App\\Controller\\TeamController::getTeams' => '?',
            'App\\Controller\\TeamController::softDeleteOneTeam' => '?',
            'App\\Controller\\TeamController::updateTeam' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\PictureController:createPicture' => '?',
            'App\\Controller\\PictureController:getPicture' => '?',
            'App\\Controller\\PictureController:softDeletePicture' => '?',
            'App\\Controller\\RecontreController:getOneRencontre' => '?',
            'App\\Controller\\RecontreController:getOneTeamRatio' => '?',
            'App\\Controller\\RecontreController:getRencontreByTeam' => '?',
            'App\\Controller\\RecontreController:getRencontres' => '?',
            'App\\Controller\\TeamController:createTeam' => '?',
            'App\\Controller\\TeamController:deleteTeam' => '?',
            'App\\Controller\\TeamController:getOneTeam' => '?',
            'App\\Controller\\TeamController:getTeams' => '?',
            'App\\Controller\\TeamController:softDeleteOneTeam' => '?',
            'App\\Controller\\TeamController:updateTeam' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
