<?php

namespace ContainerZeCxUVt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FuGjA_8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FuGjA.8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FuGjA.8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'team' => ['privates', '.errored..service_locator.FuGjA.8.App\\Entity\\Team', NULL, 'Cannot autowire service ".service_locator.FuGjA.8": it references class "App\\Entity\\Team" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'team' => 'App\\Entity\\Team',
        ]);
    }
}
