<?php

namespace ContainerZeCxUVt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KLAOo3xService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kLAOo3x' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kLAOo3x'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cache' => ['privates', 'cache.app.taggable', 'getCache_App_TaggableService', true],
            'pictureRepository' => ['privates', 'App\\Repository\\PictureRepository', 'getPictureRepositoryService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', true],
        ], [
            'cache' => '?',
            'pictureRepository' => 'App\\Repository\\PictureRepository',
            'serializer' => '?',
        ]);
    }
}
