<?php

namespace ContainerZeCxUVt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioApiDoc_Describers_ConfigService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'nelmio_api_doc.describers.config' shared service.
     *
     * @return \Nelmio\ApiDocBundle\Describer\ExternalDocDescriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/api-doc-bundle/Describer/DescriberInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/nelmio/api-doc-bundle/Describer/ExternalDocDescriber.php';

        return $container->privates['nelmio_api_doc.describers.config'] = new \Nelmio\ApiDocBundle\Describer\ExternalDocDescriber(['info' => ['title' => 'FOOTIX API', 'description' => 'This is an awesome API REST for results Football.', 'version' => '1.0.0'], 'components' => ['securitySchemes' => ['Bearer' => ['type' => 'http', 'scheme' => 'bearer', 'bearerFormat' => 'JWT', 'in' => 'header']]], 'security' => [0 => ['Bearer' => []]], 'paths' => ['/api/login_check' => ['post' => ['tags' => [0 => 'Login'], 'summary' => 'Login into the api.', 'requestBody' => ['content' => ['application/json' => ['schema' => ['properties' => ['username' => ['type' => 'string'], 'password' => ['type' => 'string']], 'type' => 'object']]]], 'responses' => [200 => ['description' => 'OK', 'content' => ['application/json' => ['schema' => ['type' => 'object', 'properties' => ['token' => ['type' => 'string'], 'refresh_token' => ['type' => 'string']]]]]], 401 => ['description' => 'Invalid credentials'], 400 => ['description' => 'Invalid JSON.']], 'security' => []]], '/api/token/refresh' => ['post' => ['tags' => [0 => 'Login'], 'summary' => 'Login into the api by refresh token.', 'requestBody' => ['content' => ['application/json' => ['schema' => ['properties' => ['refresh_token' => ['type' => 'string']], 'type' => 'object']]]], 'responses' => [200 => ['description' => 'OK', 'content' => ['application/json' => ['schema' => ['type' => 'object', 'properties' => ['token' => ['type' => 'string'], 'refresh_token' => ['type' => 'string']]]]]], 401 => ['description' => 'An authentication exception occurred.']], 'security' => []]]]]);
    }
}
