<?php

namespace ContainerZeCxUVt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRencontreService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.8ON5BGE.App\Entity\Rencontre' shared service.
     *
     * @return \App\Entity\Rencontre
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.8ON5BGE": it references class "App\\Entity\\Rencontre" but no such service exists.');
    }
}
