<?php

namespace ContainerZeCxUVt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTeamService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.FuGjA.8.App\Entity\Team' shared service.
     *
     * @return \App\Entity\Team
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.FuGjA.8": it references class "App\\Entity\\Team" but no such service exists.');
    }
}
